#!/bin/sh

OWNER="webapps"
NAME="APPNAME"
PORT=5000
WORKERS=4

VIRTUALENV="www.bearsted.cc"
APPDIR="/home/$OWNER/apps/$VIRTUALENV/$NAME"
VIRTUALENVDIR="/home/$OWNER/.py"
GUNICORN_RUN="$VIRTUALENVDIR/$VIRTUALENV/bin/gunicorn"
PID="$APPDIR/gunicorn_$NAME.pid"
VENV_ACTIVATION="source $VIRTUALENVDIR/$VIRTUALENV/bin/activate ; source $VIRTUALENVDIR/$VIRTUALENV/bin/postactivate"
RETVAL=0

# source function library
. /lib/lsb/init-functions

start()
{
    echo "Starting $NAME."
    su -c "$VENV_ACTIVATION; gunicorn -b 127.0.0.1:5000 $NAME.wsgi:application -w 4 -D --chdir $APPDIR -p $PID" $OWNER && echo "OK" || echo "failed";
}

stop()
{
    echo "Stopping $NAME"
    kill -QUIT `cat $PID` && echo "OK" || echo "failed";
}

reload()
{
    echo "Reloading $NAME:"
    if [ -f $PID ]
    then kill -HUP `cat $PID` && echo "OK" || echo "failed";
    fi
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        reload
        ;;
    reload)
        reload
        ;;
    force-reload)
        stop && start
        ;;
    *)
        echo $"Usage: $0 {start|stop|restart}"
        RETVAL=1
esac
exit $RETVAL
